app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', [
    'as' => 'home', 
    'uses' =>  'PostController@index'
]);

Route::get('/login',[
    'as'    => 'login_path',
    'uses'  => 'SessionController@create'
]);

Route::get('/logout', [
    'as'    => 'logout_path',
    'uses'  => 'SessionController@destroy'
]);

Route::resource('session', 'SessionController' );
Route::resource('post', 'PostController' );

Route::group(['before' => 'auth'], function(){

    Route::resource('user', 'UserController' );
    
});

app/models/Post.php
<?php
use Carbon\Carbon;

class Post extends \Eloquent {
    /**
     *  Protected fields from being filled in
     * @var type Array
     */
    protected $fillable = ['published', 'user_id', 'body', 'title'];

    /**
     * Validation for a post type
     * @var array
     */
    public static $rules = [
        'title'     =>      'required|min:5',
        'body'      =>      'required|min:5',
        'user_id'    =>      'required',
        
    ];

    /**
     * Changes how the date is outputed
     * https://coderwall.com/p/ms-a1g/change-created_at-display-format-globally-in-laravel-4
     * @param type $attr
     * @return Date formated at Month Day Yeat
     */
    public  function getCreatedAtAttribute($attr){
        return Carbon::parse($attr)->format('F jS Y');
    }
}

app/controllers/PostController.php
<?php

class PostController extends \BaseController {

        /**
         * Only allow index and show to be shown when not logged in
         */
        function __construct() {
            $this->beforeFilter('auth',  ['except' => ['index', 'show']]);
        }
    
	/**
	 * Display a listing of the resource.
	 * GET /post
	 *
	 * @return Response
	 */
	public function index()
	{
            
            $posts = Post::orderBy('created_at', 'DESC')->get();
            return View::make('posts.index', compact('posts'));
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /post/create
	 *
	 * @return Response
	 */
	public function create()
	{
		//
              return View::make('posts.create');
	}

	/**
	 * Store a the post for the page
	 * POST /post
	 *
	 * @return Response
	 */
	public function store()
	{
            $input      = Input::all();
            $validator  =  Validator::make($input, Post::$rules);
            
            if ($validator->failed()) {
                return Redirect::back()->withErrors($validator)->withInput();
            }
            
            $createdPost = Post::create([
                'title'     => $input['title'],
                'body'      => $input['body'],
                'published' => 0,
                'user_id'   => 1
            ]);
            
            return Redirect::route('post.edit', $createdPost->id);
	}

	/**
	 * Display the individual post
	 * GET /post/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
            $post = Post::findOrFail($id);
            return View::make('posts.show', compact('post'));
	}

	/**
	 * Edit the form
	 * GET /post/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
            $post = Post::find($id);
            Return View::make('posts.edit', compact('post'));
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /post/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
            $post = Post::findOrfail($id);
            $input = Input::all();
            $validator = Validator::make($input, Post::$rules);
            
            if ($validator->failed()) {
                return Redirect::back()->withInput();
            }

            $post->title         = $input['title'];
            $post->body          = $input['body'];
            $post->published     = $input['published'];
            $post->user_id       = 1;
            $post->save();
            
            return Redirect::back();
	}

	/**
	 * Remove the post
	 * DELETE /post/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
            Post::findOrFail($id)->delete();
            return Redirect::route('home')->with('flash_message', 'Post Deleted');
	}

}

app/views/posts/create.blade.php
@extends('layouts.default')

@section('content')
{{ Form::open(['route' => 'post.store']) }}
    @include('posts.shared.form')
{{ Form::close() }}



@stop

app/views/posts/edit.blade.php
@extends('layouts.default')

@section('content')
{{ Form::model($post, ['method' => 'PATCH', 'route' => ['post.update', $post->id]]) }}
    {{ Form::hidden('published', $post->published) }}
    @include('posts.shared.form')
{{ Form::close() }}

{{ link_to_action('PostController@show', 'View Post', $post->id) }}
{{ Form::open(['route' => ['post.destroy', $post->id], 'method' => 'DELETE']) }}
    {{ Form::submit('Delete Post') }}
{{ Form::close() }}

@stop

app/views/posts/index.blade.php
@extends('layouts.default')

@section('content')
<ul>
@foreach ($posts as $post)
<li>
    <h2>{{ link_to_route('post.show', $post->title, $post->id) }}</h2>
    <small>{{ $post->created_at }}</small>
    <div>{{ Markdown::string($post->body) }}</div>
    @if (Auth::check())
    <p>{{ link_to_route('post.edit', 'Edit Post', $post->id) }}</p>
    @endif
</li>
@endforeach 
</ul>
@stop

app/views/posts/show.blade.php
@extends('layouts.default')

@section('content')
<h1>{{ $post->title }}</h1>
<div>{{ Markdown::string($post->body) }}</div>
@if (Auth::check())
    {{ link_to_action('PostController@edit', 'Edit Post', $post->id) }}
    {{ Form::open(['route' => ['post.destroy', $post->id], 'method' => 'DELETE']) }}
        {{ Form::submit('Delete Post') }}
    {{ Form::close() }}
@endif
@stop