app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', [
    'as' => 'home', 
    'uses' =>  'PostController@index'
]);

Route::get('/login',[
    'as'    => 'login_path',
    'uses'  => 'SessionController@create'
]);

Route::get('/logout', [
    'as'    => 'logout_path',
    'uses'  => 'SessionController@destroy'
]);

Route::resource('session', 'SessionController' );
Route::resource('post', 'PostController' );

Route::group(['before' => 'auth'], function(){

    Route::resource('user', 'UserController' );
    
});

app/views/common/header.blade.php
<div id="header">
    {{ link_to_route('home', 'Simple Blog', null, ['class' => 'header__logo']) }}
    @if (Auth::check())
    {{ link_to_route('post.create', 'New Post') }}
        {{ link_to_route('logout_path', 'Logout') }}
    @endif
</div>  

app/views/common/messages.blade.php
            @if (Session::get('flash_message'))
                <div class="container flash-message">
                        <div class="bs-callout bs-callout-warning">	
                            <p>{{ Session::get('flash_message')}}</p>
                            @if ($errors)
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif						
                        </div><!-- .bs-callout bs-callout-warning -->
                </div><!-- .flashmessage -->
            @endif